### PR TITLE
Users registration and login

### PR DESCRIPTION
**Pull request by vleveris**

### CODE REVIEW

**Review by EvalVis — CHANGES_REQUESTED** [review]
When registering, you can only choose courier, choosing sender gives error and does not allow to register.
Also, when updating user it creates a new user instead of editing the existing one.

**Comment by EvalVis** [comment]
OK, the updating problem is fixed, basically, when doing an update do not create a new instance, use the old one so the old one is replaced in the db.

**Comment by vleveris** [comment]
Which error do you get @Boulderis when registering sender?

**Comment by EvalVis** [comment]
@vleveris Role field is required.

**Comment by vleveris** [comment]
Sender is not default, you need to click on it in a dropdown list so that it would be selected.

**Comment by EvalVis** [comment]
There are only two fields: sender and courier, sender is the default. The error persist even if I click on it to be sure.

**Comment by EvalVis** [comment]
It's fine with courier however.

**Comment by vleveris** [comment]
Well, strange then, sender registration works for me either. Try changing role to courier and then back to sender.

**Comment by EvalVis** [comment]
Thanks, that worked. However, that should be fixed either leaving role as not selected at the start or allowing to register when Sender is selected and no switches are done.

**Comment by vleveris** [comment]
Yes, I may change that, however I didn't want to make some role default one.

**Comment by EvalVis** [comment]
Maybe it could depend on the browser but as I said, the sender is the default one for me but it does not allow to register with it (only with switch to courier and back trick it works).

**Comment by vleveris** [comment]
@Boulderis what do you think about this approach?

**Comment by EvalVis** [comment]
@vleveris It does work, thanks.

**Review by EvalVis — APPROVED** [review]
The bugs, I found have been fixed. I approve.

**Comment by vleveris** [comment]
Currently there is an issue related to user updating (cookie does not get changed after updating). When user changes his/her username, on the main page old username is shown and it is correct when signing out and loging in again. This is because I use blazor component in update page and cannot use IHttpContextAccessor. Maybe it could be done using .cshtml file but then I think some other problems could occur (will discuss that in a meeting).

**Comment by yjhn** [comment]
Let's not worry about updating usernames and such things. It's nice to have these, but it's not neccessary.

**Pull request merged**
